[project]
name = "product-demand-inventory-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ujwala4", email = "ujwala@ictsystemsindia.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
product-demand-inventory-analyzer = "product_demand_inventory_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
